# Generated by Django 4.2.11 on 2024-04-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan_ip.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('so', models.CharField(blank=True, max_length=100, null=True)),
                ('archi', models.CharField(blank=True, max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('install_date', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('procesador', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=100, null=True)),
                ('storage1', models.CharField(blank=True, max_length=100, null=True)),
                ('storage2', models.CharField(blank=True, max_length=100, null=True)),
                ('ipv4', models.CharField(blank=True, max_length=100, null=True)),
                ('dirmac', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scan_ip.responsable')),
            ],
        ),
    ]
